import { useEffect, useRef, useState } from 'react';
import { Check, Clock, Gift, Image as ImageIcon, Loader2, Pencil, Plus, Save, Search, Tag, ToggleLeft, ToggleRight, Trash2, X, Zap } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Tenant } from '@/lib/types';
import { DAY_NAMES_SHORT_ES, formatActiveDays, isPromotionCurrentlyActive } from '@/lib/promoSchedule';

type Section = 'promotions' | 'coupons' | 'rewards' | 'automations';
interface Promotion { id:string; name:string; description:string|null; type:string; value:number|null; discount_pct?:number|null; discount_fixed?:number|null; min_order_amount:number|null; level_required:string|null; active_hours_start:string|null; active_hours_end:string|null; start_time?:string|null; end_time?:string|null; active_days:number[]|null; active_until:string|null; item_ids:string[]|null; promo_price:number|null; image_url:string|null; badge_text:string|null; is_active:boolean; is_new_customer:boolean; is_reactivation:boolean; created_at:string; }
interface Coupon { id:string; code:string; discount_pct?:number|null; discount_fixed?:number|null; discount_type?:string|null; discount_value?:number|null; max_uses:number|null; used_count:number; is_active:boolean; }
interface Reward { id:string; name:string; points_required:number; reward_value:number; is_active:boolean; }
interface Automation { id:string; trigger_type:string; is_active:boolean; }
interface MenuItem { id:string; name:string; price:number; image_url:string|null; }

const PROMO_TYPES = [ ['percentage','Descuento %','🏷️'], ['fixed','Descuento fijo','💵'], ['2x1','2×1','🎁'], ['combo','Combo','🍱'], ['schedule','Por horario','🕐'], ['level','Por nivel','⭐'], ['new_customer','Cliente nuevo','👋'], ['reactivation','Reactivación','🔄'] ] as const;
const AUTO = [ ['first_order','Primer pedido','Enviar cupón de bienvenida'], ['inactive_30','Inactivo 30 días','Enviar cupón de reactivación'], ['birthday','Cumpleaños','Enviar beneficio'], ['reward_available','Recompensa disponible','Notificar al cliente'], ['cart_abandoned','Carrito abandonado','Recordatorio de carrito'] ] as const;
const LEVELS = ['bronze','silver','gold','vip'];
const inputCls = 'w-full px-3 py-2 rounded-xl text-sm bg-transparent outline-none';
const inputStyle = { border:'1px solid var(--border)', color:'var(--text-primary)' };

function url(u?: string|null) { if (!u) return ''; return u.startsWith('http') || u.startsWith('data:') || u.startsWith('/') ? u : `/${u}`; }
function dateLocal(v?: string|null) { if (!v) return ''; const d = new Date(v); if (Number.isNaN(d.getTime())) return ''; const p=(n:number)=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; }
async function compress(file:File) { return new Promise<Blob>((resolve,reject)=>{ const img=new Image(); const o=URL.createObjectURL(file); img.onload=()=>{ URL.revokeObjectURL(o); let w=img.width,h=img.height; if(w>1200){h=Math.round(h*1200/w);w=1200;} const c=document.createElement('canvas'); c.width=w;c.height=h; const ctx=c.getContext('2d'); if(!ctx)return reject(new Error('Canvas no disponible')); ctx.drawImage(img,0,0,w,h); c.toBlob(b=>b?resolve(b):reject(new Error('No se pudo comprimir')),'image/webp',0.84); }; img.onerror=()=>reject(new Error('No se pudo leer la imagen')); img.src=o; }); }
async function dataUrl(blob:Blob){ return new Promise<string>((res,rej)=>{ const r=new FileReader(); r.onload=()=>res(String(r.result||'')); r.onerror=()=>rej(new Error('No se pudo leer')); r.readAsDataURL(blob); }); }

export default function PromotionsTab({ tenant }: { tenant: Tenant }) {
  const [section,setSection]=useState<Section>('promotions');
  const [promos,setPromos]=useState<Promotion[]>([]), [coupons,setCoupons]=useState<Coupon[]>([]), [rewards,setRewards]=useState<Reward[]>([]), [autos,setAutos]=useState<Automation[]>([]), [items,setItems]=useState<MenuItem[]>([]);
  const [loading,setLoading]=useState(true), [showForm,setShowForm]=useState(false), [editing,setEditing]=useState<string|null>(null), [saving,setSaving]=useState(false), [uploading,setUploading]=useState(false), [savingAuto,setSavingAuto]=useState<string|null>(null);
  const fileRef=useRef<HTMLInputElement|null>(null);
  const [name,setName]=useState(''), [desc,setDesc]=useState(''), [type,setType]=useState('percentage'), [pct,setPct]=useState(''), [fixed,setFixed]=useState(''), [price,setPrice]=useState(''), [min,setMin]=useState(''), [level,setLevel]=useState(''), [img,setImg]=useState(''), [badge,setBadge]=useState(''), [until,setUntil]=useState('');
  const [start,setStart]=useState(''), [end,setEnd]=useState(''), [days,setDays]=useState<number[]>([0,1,2,3,4,5,6]), [always,setAlways]=useState(true), [visibleOnly,setVisibleOnly]=useState(true), [newOnly,setNewOnly]=useState(false), [reactivation,setReactivation]=useState(false), [selected,setSelected]=useState<string[]>([]), [q,setQ]=useState(''), [showItems,setShowItems]=useState(false);
  const [couponCode,setCouponCode]=useState(''), [couponPct,setCouponPct]=useState(''), [couponFixed,setCouponFixed]=useState(''), [showCoupon,setShowCoupon]=useState(false);
  const [rewardName,setRewardName]=useState(''), [rewardPoints,setRewardPoints]=useState(''), [rewardValue,setRewardValue]=useState(''), [showReward,setShowReward]=useState(false);

  async function load(){ setLoading(true); const [p,c,r,a,i]=await Promise.all([ supabase.from('promotions').select('*').eq('tenant_id',tenant.id).order('created_at',{ascending:false}), supabase.from('coupons').select('*').eq('tenant_id',tenant.id).order('created_at',{ascending:false}), supabase.from('loyalty_rewards').select('*').eq('tenant_id',tenant.id).order('points_required'), supabase.from('automation_rules').select('*').eq('tenant_id',tenant.id), supabase.from('menu_items').select('id,name,price,image_url').eq('tenant_id',tenant.id).order('name') ]); setPromos((p.data||[]) as Promotion[]); setCoupons((c.data||[]) as Coupon[]); setRewards((r.data||[]) as Reward[]); setAutos((a.data||[]) as Automation[]); setItems((i.data||[]) as MenuItem[]); setLoading(false); }
  useEffect(()=>{ load(); },[tenant.id]);
  function reset(){ setEditing(null); setName('');setDesc('');setType('percentage');setPct('');setFixed('');setPrice('');setMin('');setLevel('');setImg('');setBadge('');setUntil('');setStart('');setEnd('');setDays([0,1,2,3,4,5,6]);setAlways(true);setVisibleOnly(true);setNewOnly(false);setReactivation(false);setSelected([]);setQ('');setShowItems(false); }
  function edit(p:Promotion){ setEditing(p.id); setName(p.name||''); setDesc(p.description||''); setType(p.type||'percentage'); setPct(['percentage','level','new_customer','reactivation'].includes(p.type)?String(p.value||p.discount_pct||''):''); setFixed(p.type==='fixed'?String(p.value||p.discount_fixed||''):''); setPrice(p.promo_price?String(p.promo_price):''); setMin(p.min_order_amount?String(p.min_order_amount):''); setLevel(p.level_required||''); setImg(p.image_url||''); setBadge(p.badge_text||''); setUntil(dateLocal(p.active_until)); setStart(p.active_hours_start||p.start_time||''); setEnd(p.active_hours_end||p.end_time||''); setDays(Array.isArray(p.active_days)?p.active_days:[0,1,2,3,4,5,6]); setAlways(!p.active_days && !p.active_hours_start && !p.start_time); setVisibleOnly(true); setNewOnly(!!p.is_new_customer); setReactivation(!!p.is_reactivation); setSelected(Array.isArray(p.item_ids)?p.item_ids:[]); setShowForm(true); }
  async function upload(file:File){ setUploading(true); try{ const blob=await compress(file); const path=`${tenant.id}/promotions/${editing||'draft'}-${Date.now()}.webp`; const up=await supabase.storage.from('menu-images').upload(path,blob,{contentType:'image/webp',cacheControl:'31536000',upsert:true}); if(!up.error){ setImg(supabase.storage.from('menu-images').getPublicUrl(path).data.publicUrl); } else setImg(await dataUrl(blob)); }catch(e){ console.error(e); alert('No se pudo subir la imagen.'); } finally { setUploading(false); } }
  async function savePromo(){ if(!name.trim())return; setSaving(true); const value=['percentage','level','new_customer','reactivation'].includes(type)?Number(pct||0):type==='fixed'?Number(fixed||0):0; const payload={ tenant_id:tenant.id, name:name.trim(), description:desc.trim()||null, type, value, min_order_amount:min?Number(min):null, level_required:level||null, active_hours_start:always?null:(start||null), active_hours_end:always?null:(end||null), active_days:always?null:(days.length===7?null:days), active_until:until?new Date(until).toISOString():null, item_ids:selected.length?selected:null, promo_price:price?Number(price):null, image_url:img.trim()||null, badge_text:badge.trim()||null, is_active:true, is_new_customer:newOnly, is_reactivation:reactivation } as any; const res=editing?await supabase.from('promotions').update(payload).eq('id',editing).eq('tenant_id',tenant.id):await supabase.from('promotions').insert(payload); setSaving(false); if(res.error){ console.error('Error saving promotion', res.error); alert(`No se pudo guardar la promoción: ${res.error.message}`); return; } setShowForm(false); reset(); load(); }
  async function togglePromo(id:string,current:boolean){ const {error}=await supabase.from('promotions').update({is_active:!current}).eq('id',id); if(!error)setPromos(v=>v.map(p=>p.id===id?{...p,is_active:!current}:p)); }
  async function delPromo(id:string){ if(!confirm('¿Eliminar esta promoción?'))return; const {error}=await supabase.from('promotions').delete().eq('id',id); if(!error)setPromos(v=>v.filter(p=>p.id!==id)); }
  const filtered=items.filter(i=>i.name.toLowerCase().includes(q.toLowerCase())); const preview=url(img||items.find(i=>selected.includes(i.id)&&i.image_url)?.image_url||'');

  async function saveCoupon(){ if(!couponCode.trim())return; await supabase.from('coupons').insert({tenant_id:tenant.id,code:couponCode.trim().toUpperCase(),discount_type:couponPct?'percentage':'fixed',discount_value:Number(couponPct||couponFixed||0),is_active:true,used_count:0}); setShowCoupon(false); setCouponCode('');setCouponPct('');setCouponFixed(''); load(); }
  async function saveReward(){ if(!rewardName.trim()||!rewardPoints)return; await supabase.from('loyalty_rewards').insert({tenant_id:tenant.id,name:rewardName.trim(),points_required:Number(rewardPoints),reward_value:Number(rewardValue||0),is_active:true}); setShowReward(false); setRewardName('');setRewardPoints('');setRewardValue(''); load(); }
  async function toggleAuto(key:string){ setSavingAuto(key); const at=AUTO.find(a=>a[0]===key); const ex=autos.find(a=>a.trigger_type===key); if(ex) await supabase.from('automation_rules').update({is_active:!ex.is_active}).eq('id',ex.id); else if(at) await supabase.from('automation_rules').insert({tenant_id:tenant.id,name:at[1],trigger_type:key,action_type:'send_coupon',action_config:{description:at[2]},is_active:true}); setSavingAuto(null); load(); }

  return <div>
    <h2 className="text-lg font-black text-[var(--text-primary)] mb-4">Motor de Promociones</h2>
    <div className="flex gap-2 overflow-x-auto pb-2 mb-4">{([['promotions','Promociones',<Tag size={14}/>],['coupons','Cupones',<Gift size={14}/>],['rewards','Recompensas',<Tag size={14}/>],['automations','Automatiz.',<Zap size={14}/>]] as const).map(s=><button key={s[0]} onClick={()=>setSection(s[0])} className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold whitespace-nowrap" style={{background:section===s[0]?'#F59E0B':'rgba(255,255,255,.06)',color:section===s[0]?'#000':'#94A3B8'}}>{s[2]} {s[1]}</button>)}</div>
    {loading ? <div className="flex justify-center py-12"><Loader2 size={24} className="animate-spin text-slate-500"/></div> : <>
      {section==='promotions' && <div>
        <button onClick={()=>{showForm?setShowForm(false):(reset(),setShowForm(true));}} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold mb-4" style={{background:'#F59E0B',color:'#000'}}>{showForm?<X size={16}/>:<Plus size={16}/>} {showForm?'Cerrar editor':'Nueva promoción'}</button>
        {showForm && <div className="rounded-2xl p-4 mb-4 space-y-4" style={{background:'var(--bg-surface)',border:'1px solid var(--border)'}}>
          <div className="flex justify-between gap-3"><div><div className="text-sm font-black text-[var(--text-primary)]">{editing?'Editar promoción':'Nueva promoción'}</div><div className="text-xs text-slate-500">Edita texto, precio, platillos, horario e imagen aquí mismo.</div></div>{editing&&<span className="text-[10px] px-2 py-1 rounded-full bg-amber-500/15 text-amber-400 font-bold">Editando</span>}</div>
          <input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre" className={inputCls} style={inputStyle}/><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Descripción" rows={2} className={inputCls} style={inputStyle}/>
          <div className="rounded-2xl p-3" style={{background:'rgba(255,255,255,.035)',border:'1px solid var(--border)'}}><div className="flex gap-3 items-start"><div className="w-28 h-24 rounded-2xl overflow-hidden bg-black/30 flex items-center justify-center border border-white/10">{preview?<img src={preview} className="w-full h-full object-cover"/>:<ImageIcon className="text-slate-600"/>}</div><div className="flex-1 min-w-0"><label className="text-xs font-bold text-amber-400 block mb-1">Foto principal</label><div className="flex gap-2"><button type="button" onClick={()=>fileRef.current?.click()} disabled={uploading} className="px-3 py-2 rounded-xl text-xs font-bold bg-amber-500 text-black">{uploading?'Subiendo...':'Subir foto'}</button>{img&&<button type="button" onClick={()=>setImg('')} className="px-3 py-2 rounded-xl text-xs font-bold bg-red-500/15 text-red-400">Quitar</button>}</div><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0]; if(f)upload(f); e.currentTarget.value='';}}/><input value={img} onChange={e=>setImg(e.target.value)} placeholder="URL o foto subida" className={`${inputCls} mt-2 text-xs`} style={inputStyle}/><p className="text-[11px] text-slate-500 mt-1">Si queda vacío, usa la foto del primer platillo seleccionado.</p></div></div></div>
          <div className="grid grid-cols-2 gap-2">{PROMO_TYPES.map(t=><button key={t[0]} type="button" onClick={()=>setType(t[0])} className="flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-semibold" style={{background:type===t[0]?'#F59E0B22':'rgba(255,255,255,.04)',border:`1px solid ${type===t[0]?'#F59E0B':'transparent'}`,color:type===t[0]?'#F59E0B':'#94A3B8'}}>{t[2]} {t[1]}</button>)}</div>
          {['percentage','level','new_customer','reactivation'].includes(type)&&<input value={pct} onChange={e=>setPct(e.target.value)} placeholder="Descuento %" type="number" className={inputCls} style={inputStyle}/>} {type==='fixed'&&<input value={fixed} onChange={e=>setFixed(e.target.value)} placeholder="Descuento fijo ₡" type="number" className={inputCls} style={inputStyle}/>} {type==='level'&&<select value={level} onChange={e=>setLevel(e.target.value)} className={inputCls} style={inputStyle}><option value="">Todos</option>{LEVELS.map(l=><option key={l} value={l}>{l}</option>)}</select>}
          <div className="grid grid-cols-2 gap-2"><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Precio final promo" type="number" className={inputCls} style={inputStyle}/><input value={badge} onChange={e=>setBadge(e.target.value)} placeholder="Etiqueta: PAGO FINAL" className={inputCls} style={inputStyle}/></div><input value={min} onChange={e=>setMin(e.target.value)} placeholder="Monto mínimo opcional" type="number" className={inputCls} style={inputStyle}/>
          <button type="button" onClick={()=>setShowItems(v=>!v)} className="flex items-center justify-between w-full px-3 py-2 rounded-xl text-xs font-semibold" style={{background:'rgba(255,255,255,.04)',border:'1px solid var(--border)',color:'#94A3B8'}}><span>{selected.length?`${selected.length} platillos seleccionados`:'Platillos incluidos o relacionados'}</span><span>{showItems?'▲':'▼'}</span></button>{showItems&&<div className="rounded-xl overflow-hidden" style={{border:'1px solid var(--border)'}}><div className="flex items-center gap-2 px-3 py-2"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar platillo" className="flex-1 bg-transparent text-xs outline-none text-[var(--text-primary)]"/></div><div className="max-h-56 overflow-y-auto">{filtered.map(i=>{const sel=selected.includes(i.id);return <button key={i.id} type="button" onClick={()=>setSelected(v=>sel?v.filter(x=>x!==i.id):[...v,i.id])} className="flex items-center gap-2 w-full px-3 py-2 text-xs text-left" style={{background:sel?'#F59E0B15':'transparent',color:sel?'#F59E0B':'#94A3B8'}}><span className="w-4 h-4 rounded flex items-center justify-center" style={{background:sel?'#F59E0B':'rgba(255,255,255,.08)'}}>{sel&&<Check size={10} className="text-black"/>}</span><span className="w-8 h-8 rounded-lg overflow-hidden bg-black/30 flex items-center justify-center">{i.image_url?<img src={url(i.image_url)} className="w-full h-full object-cover"/>:<ImageIcon size={13}/>}</span><span className="flex-1 truncate">{i.name}</span><span>₡{i.price?.toLocaleString()}</span></button>})}</div></div>}
          <div className="rounded-xl p-3 space-y-3" style={{background:'rgba(245,158,11,.06)',border:'1px solid rgba(245,158,11,.2)'}}><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={always} onChange={e=>setAlways(e.target.checked)} className="accent-amber-400"/>Siempre activa</label>{!always&&<><div className="flex gap-1.5 flex-wrap">{([1,2,3,4,5,6,0] as number[]).map(d=>{const sel=days.includes(d);return <button key={d} type="button" onClick={()=>setDays(v=>sel?v.filter(x=>x!==d):[...v,d])} className="px-2 py-1 rounded-lg text-xs font-semibold" style={{background:sel?'#F59E0B':'rgba(255,255,255,.06)',color:sel?'#000':'#94A3B8'}}>{DAY_NAMES_SHORT_ES[d]}</button>})}</div><div className="grid grid-cols-2 gap-2"><input type="time" value={start} onChange={e=>setStart(e.target.value)} className={inputCls} style={inputStyle}/><input type="time" value={end} onChange={e=>setEnd(e.target.value)} className={inputCls} style={inputStyle}/></div></>}<input type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)} className={inputCls} style={inputStyle}/><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={visibleOnly} onChange={e=>setVisibleOnly(e.target.checked)} className="accent-amber-400"/>Solo visible durante horario activo</label></div>
          <div className="flex gap-4"><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={newOnly} onChange={e=>setNewOnly(e.target.checked)}/>Solo clientes nuevos</label><label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={reactivation} onChange={e=>setReactivation(e.target.checked)}/>Reactivación</label></div><div className="flex gap-2"><button onClick={()=>{setShowForm(false);reset();}} className="flex-1 py-2 rounded-xl text-sm text-slate-400">Cancelar</button><button onClick={savePromo} disabled={saving||uploading} className="flex-1 py-2 rounded-xl text-sm font-bold flex items-center justify-center gap-2" style={{background:'#F59E0B',color:'#000'}}>{saving?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>} Guardar</button></div>
        </div>}
        <div className="space-y-2">{promos.length===0?<p className="text-sm text-slate-500 text-center py-8">No hay promociones aún</p>:promos.map(p=>{const t=PROMO_TYPES.find(x=>x[0]===p.type);const pic=url(p.image_url||items.find(i=>p.item_ids?.includes(i.id)&&i.image_url)?.image_url||'');return <div key={p.id} className="flex items-center gap-3 px-3 py-3 rounded-xl" style={{background:'var(--bg-surface)',border:'1px solid rgba(255,255,255,.06)'}}><div className="w-16 h-14 rounded-xl overflow-hidden bg-black/30 flex items-center justify-center">{pic?<img src={pic} className="w-full h-full object-cover"/>:<span>{t?.[2]||'🏷️'}</span>}</div><div className="flex-1 min-w-0"><div className="text-sm font-semibold text-[var(--text-primary)] truncate">{p.name}</div><div className="text-xs text-slate-400 truncate">{t?.[1]} · <span className="font-semibold text-amber-400">{p.promo_price?`₡${p.promo_price.toLocaleString()}`:p.type==='percentage'?`${p.value||0}%`:p.type==='fixed'?`₡${p.value||0}`:''}</span>{p.item_ids?.length?` · ${p.item_ids.length} platillos`:''}</div>{(p.active_days||p.active_hours_start)&&<div className="text-[10px] text-slate-500 mt-.5 flex items-center gap-1"><Clock size={9}/>{formatActiveDays(p.active_days)}{(p.active_hours_start||p.start_time)&&` · ${p.active_hours_start||p.start_time}–${p.active_hours_end||p.end_time}`}</div>}{p.is_active&&<div className={`text-[10px] font-semibold ${isPromotionCurrentlyActive(p)?'text-green-400':'text-red-400'}`}>{isPromotionCurrentlyActive(p)?'● Activa ahora':'○ Fuera de horario'}</div>}</div><div className="flex items-center gap-2"><button onClick={()=>edit(p)}><Pencil size={15} className="text-slate-400 hover:text-amber-400"/></button><button onClick={()=>togglePromo(p.id,p.is_active)}>{p.is_active?<ToggleRight size={22} className="text-amber-400"/>:<ToggleLeft size={22} className="text-slate-500"/>}</button><button onClick={()=>delPromo(p.id)}><Trash2 size={15} className="text-slate-500 hover:text-red-400"/></button></div></div>})}</div>
      </div>}
      {section==='coupons'&&<div><button onClick={()=>setShowCoupon(v=>!v)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold mb-4" style={{background:'#F59E0B',color:'#000'}}><Plus size={16}/> Nuevo cupón</button>{showCoupon&&<div className="rounded-2xl p-4 mb-4 space-y-3" style={{background:'var(--bg-surface)',border:'1px solid var(--border)'}}><input value={couponCode} onChange={e=>setCouponCode(e.target.value)} placeholder="Código" className={inputCls} style={inputStyle}/><div className="grid grid-cols-2 gap-2"><input value={couponPct} onChange={e=>setCouponPct(e.target.value)} placeholder="%" type="number" className={inputCls} style={inputStyle}/><input value={couponFixed} onChange={e=>setCouponFixed(e.target.value)} placeholder="₡" type="number" className={inputCls} style={inputStyle}/></div><button onClick={saveCoupon} className="w-full py-2 rounded-xl text-sm font-bold" style={{background:'#F59E0B',color:'#000'}}>Guardar</button></div>}<div className="space-y-2">{coupons.map(c=><div key={c.id} className="flex items-center gap-3 px-3 py-3 rounded-xl" style={{background:'var(--bg-surface)',border:'1px solid rgba(255,255,255,.06)'}}><div className="flex-1"><div className="text-sm font-semibold font-mono text-[var(--text-primary)]">{c.code}</div><div className="text-xs text-slate-400">{c.discount_value||c.discount_pct||c.discount_fixed} {c.discount_type==='percentage'||c.discount_pct?'%':'₡'} · {c.used_count} usos</div></div><button onClick={async()=>{await supabase.from('coupons').delete().eq('id',c.id);load();}}><Trash2 size={14} className="text-slate-500"/></button></div>)}</div></div>}
      {section==='rewards'&&<div><button onClick={()=>setShowReward(v=>!v)} className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold mb-4" style={{background:'#F59E0B',color:'#000'}}><Plus size={16}/> Nueva recompensa</button>{showReward&&<div className="rounded-2xl p-4 mb-4 space-y-3" style={{background:'var(--bg-surface)',border:'1px solid var(--border)'}}><input value={rewardName} onChange={e=>setRewardName(e.target.value)} placeholder="Nombre" className={inputCls} style={inputStyle}/><div className="grid grid-cols-2 gap-2"><input value={rewardPoints} onChange={e=>setRewardPoints(e.target.value)} placeholder="Puntos" type="number" className={inputCls} style={inputStyle}/><input value={rewardValue} onChange={e=>setRewardValue(e.target.value)} placeholder="Valor ₡" type="number" className={inputCls} style={inputStyle}/></div><button onClick={saveReward} className="w-full py-2 rounded-xl text-sm font-bold" style={{background:'#F59E0B',color:'#000'}}>Guardar</button></div>}<div className="space-y-2">{rewards.map(r=><div key={r.id} className="flex items-center gap-3 px-3 py-3 rounded-xl" style={{background:'var(--bg-surface)',border:'1px solid rgba(255,255,255,.06)'}}><div className="flex-1"><div className="text-sm font-semibold text-[var(--text-primary)]">{r.name}</div><div className="text-xs text-slate-400">{r.points_required} puntos · ₡{r.reward_value}</div></div><button onClick={async()=>{await supabase.from('loyalty_rewards').update({is_active:!r.is_active}).eq('id',r.id);load();}}>{r.is_active?<ToggleRight size={22} className="text-amber-400"/>:<ToggleLeft size={22} className="text-slate-500"/>}</button></div>)}</div></div>}
      {section==='automations'&&<div><p className="text-xs text-slate-400 mb-4">Activa automatizaciones según comportamiento del cliente.</p><div className="space-y-3">{AUTO.map(a=>{const ex=autos.find(x=>x.trigger_type===a[0]);const active=!!ex?.is_active;return <div key={a[0]} className="flex items-center gap-3 px-3 py-3 rounded-xl" style={{background:'var(--bg-surface)',border:'1px solid rgba(255,255,255,.06)'}}><div className="flex-1"><div className="text-sm font-semibold text-[var(--text-primary)]">{a[1]}</div><div className="text-xs text-slate-400">{a[2]}</div></div><button onClick={()=>toggleAuto(a[0])} disabled={savingAuto===a[0]}>{savingAuto===a[0]?<Loader2 size={22} className="animate-spin"/>:active?<ToggleRight size={22} className="text-amber-400"/>:<ToggleLeft size={22} className="text-slate-500"/>}</button></div>})}</div></div>}
    </>}
  </div>;
}
